/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.SalesPerson;

import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

import model.Business.Business;
import model.Supplier.Supplier;
import model.UserAccountManagement.UserAccount;

import javax.swing.JOptionPane;

import model.ProductManagement.Product;
import model.ProductManagement.ProductSummary;

/**
 * @author bhargav
 */
public class ManageSuppliersJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageSuppliersJPanel
     */
    JPanel cardSequencePanel;
    Business business;
    UserAccount userAccount;

    public ManageSuppliersJPanel(JPanel cardSequencePanel, Business business, UserAccount userAccount) {
        initComponents();
        this.cardSequencePanel = cardSequencePanel;
        this.business = business;
        this.userAccount = userAccount;
        populateSupplier();
    }

    private void populateSupplier() {
        business.getSupplierDirectory().getSupplierList().forEach(supplier -> {
            cmbSupplier.addItem(supplier);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbSupplier = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductsCaltalog = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        lblSupplier = new javax.swing.JLabel();
        lblProductName = new javax.swing.JLabel();
        txtProductName = new javax.swing.JTextField();
        lblFrequencyAboveTarget = new javax.swing.JLabel();
        txtFrequencyAboveTarget = new javax.swing.JTextField();
        lblFrequencyBelowTarget = new javax.swing.JLabel();
        txtFrequencyBelowTarget = new javax.swing.JTextField();
        lblSalesRevenues = new javax.swing.JLabel();
        txtSalesRevenue = new javax.swing.JTextField();
        lblMarginAroundTarget = new javax.swing.JLabel();
        txtMarginTarget = new javax.swing.JTextField();
        btnAdjustTargetValue = new javax.swing.JButton();
        lblSuggestedTargetValue = new javax.swing.JLabel();
        txtSuggestedValue = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable12 = new javax.swing.JTable();
        lblSupplierProfit = new javax.swing.JLabel();
        txtSupplierProfit = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 204));

        cmbSupplier.setMaximumRowCount(100);
        cmbSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSupplierActionPerformed(evt);
            }
        });

        tblProductsCaltalog.setAutoCreateRowSorter(true);
        tblProductsCaltalog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Floor Price", "Ceiling Price", "Target Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProductsCaltalog.setGridColor(new java.awt.Color(0, 0, 0));
        tblProductsCaltalog.setOpaque(false);
        tblProductsCaltalog.setShowGrid(true);
        tblProductsCaltalog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductsCaltalogMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblProductsCaltalogMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblProductsCaltalog);

        btnBack.setBackground(new java.awt.Color(51, 153, 255));
        btnBack.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblSupplier.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblSupplier.setText("Supplier :");

        lblProductName.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblProductName.setText("Product Name");

        lblFrequencyAboveTarget.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblFrequencyAboveTarget.setText("Frequency Above Target");

        lblFrequencyBelowTarget.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblFrequencyBelowTarget.setText("Frequency Below Target");

        lblSalesRevenues.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblSalesRevenues.setText("Sales Revenues");

        lblMarginAroundTarget.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblMarginAroundTarget.setText("Margin Around Target");

        btnAdjustTargetValue.setBackground(new java.awt.Color(51, 153, 255));
        btnAdjustTargetValue.setForeground(new java.awt.Color(255, 255, 255));
        btnAdjustTargetValue.setText("Adjust Target Value");
        btnAdjustTargetValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdjustTargetValueActionPerformed(evt);
            }
        });

        lblSuggestedTargetValue.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblSuggestedTargetValue.setText("Suggested Target Value");

        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Target Price", "No. Sales Above Target", "No. Sales Below Target", "Profit"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jTabbedPane1.addTab("Current Target Analysis", jScrollPane3);

        jTable12.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Total Order Values", "Order Total After", "Order Total Before", "Profit Before", "Profit After"
            }
        ));
        jScrollPane2.setViewportView(jTable12);

        jTabbedPane1.addTab("New Target Analysis", jScrollPane2);

        lblSupplierProfit.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblSupplierProfit.setText("Supplier Profit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdjustTargetValue, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSupplierProfit, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSupplierProfit))
                                .addGap(240, 240, 240))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtProductName, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                        .addComponent(lblProductName))
                                    .addComponent(txtSuggestedValue, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSuggestedTargetValue))
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtFrequencyAboveTarget, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(lblFrequencyAboveTarget)
                                    .addComponent(lblSalesRevenues)
                                    .addComponent(txtSalesRevenue, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFrequencyBelowTarget, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFrequencyBelowTarget)
                            .addComponent(txtMarginTarget, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMarginAroundTarget))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lblSupplier)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cmbSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBack)
                                .addGap(596, 596, 596)))
                        .addGap(28, 28, 28))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblProductName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblFrequencyBelowTarget)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtFrequencyBelowTarget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblFrequencyAboveTarget)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtFrequencyAboveTarget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMarginAroundTarget)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMarginTarget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSalesRevenues)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSalesRevenue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSuggestedTargetValue)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSuggestedValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(lblSupplierProfit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSupplierProfit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdjustTargetValue, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Current Target Analysis");
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        cardSequencePanel.remove(this);
        CardLayout layout = (CardLayout) cardSequencePanel.getLayout();
        layout.previous(cardSequencePanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void tblProductsCaltalogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductsCaltalogMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblProductsCaltalogMouseClicked

    private void tblProductsCaltalogMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductsCaltalogMousePressed
        // TODO add your handling code here:
        populateData();
        populatePreviousData();
        populateNewData();

    }//GEN-LAST:event_tblProductsCaltalogMousePressed

    private void btnAdjustTargetValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdjustTargetValueActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblProductsCaltalog.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a product to adjust the target value");
            return;
        }
        Product prod = (Product) tblProductsCaltalog.getValueAt(selectedRow, 0);
        ProductSummary prodSummary = new ProductSummary(prod);
        prod.updateProduct(prod.getFloorPrice(), prod.getCeilingPrice(), Integer.parseInt(txtSuggestedValue.getText()));
        JOptionPane.showMessageDialog(null, "Target Value Adjusted Successfully");
        populateProducts();
    }//GEN-LAST:event_btnAdjustTargetValueActionPerformed

    private void cmbSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSupplierActionPerformed
        populateProducts();
        txtSupplierProfit.setText(String.valueOf(((Supplier) cmbSupplier.getSelectedItem()).getPricePerformance()));
    }//GEN-LAST:event_cmbSupplierActionPerformed

    private void populateProducts() {
        int selectedSupplierIndex = cmbSupplier.getSelectedIndex();
        if (selectedSupplierIndex < 0) {
            return;
        }
        DefaultTableModel dtm = (DefaultTableModel) tblProductsCaltalog.getModel();
        dtm.setRowCount(0);
        Supplier selectedSupplier = (Supplier) cmbSupplier.getSelectedItem();
        for (int i = 0; i < selectedSupplier.getProductCatalog().getProductList().size(); i++) {
            Object row[] = new Object[4];
            row[0] = selectedSupplier.getProductCatalog().getProductList().get(i);
            row[1] = selectedSupplier.getProductCatalog().getProductList().get(i).getFloorPrice();
            row[2] = selectedSupplier.getProductCatalog().getProductList().get(i).getCeilingPrice();
            row[3] = selectedSupplier.getProductCatalog().getProductList().get(i).getTargetPrice();
            dtm.addRow(row);
        }
        populateData();

    }

    public void populateData() {
        int selectedRow = tblProductsCaltalog.getSelectedRow();
        if (selectedRow < 0) {
            return;
        }
        Product prod = (Product) tblProductsCaltalog.getValueAt(selectedRow, 0);
        ProductSummary prodSummary = new ProductSummary(prod);
        txtProductName.setText(prodSummary.getProductName());
        txtFrequencyAboveTarget.setText(String.valueOf(prodSummary.getNumberAboveTarget()));
        txtFrequencyBelowTarget.setText(String.valueOf(prodSummary.getNumberBelowTarget()));
        txtSalesRevenue.setText(String.valueOf(prodSummary.getSalesRevenues()));
        txtMarginTarget.setText(String.valueOf(prodSummary.getProductPricePerformance()));

        txtSuggestedValue.setText(String.valueOf(prod.getRecommendedPrice()));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdjustTargetValue;
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox<Supplier> cmbSupplier;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable12;
    private javax.swing.JLabel lblFrequencyAboveTarget;
    private javax.swing.JLabel lblFrequencyBelowTarget;
    private javax.swing.JLabel lblMarginAroundTarget;
    private javax.swing.JLabel lblProductName;
    private javax.swing.JLabel lblSalesRevenues;
    private javax.swing.JLabel lblSuggestedTargetValue;
    private javax.swing.JLabel lblSupplier;
    private javax.swing.JLabel lblSupplierProfit;
    private javax.swing.JTable tblProductsCaltalog;
    private javax.swing.JTextField txtFrequencyAboveTarget;
    private javax.swing.JTextField txtFrequencyBelowTarget;
    private javax.swing.JTextField txtMarginTarget;
    private javax.swing.JTextField txtProductName;
    private javax.swing.JTextField txtSalesRevenue;
    private javax.swing.JTextField txtSuggestedValue;
    private javax.swing.JTextField txtSupplierProfit;
    // End of variables declaration//GEN-END:variables

    private void populatePreviousData() {
        int selectedRow = tblProductsCaltalog.getSelectedRow();
        if (selectedRow < 0) {
            return;
        }
        Product prod = (Product) tblProductsCaltalog.getValueAt(selectedRow, 0);
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
        ProductSummary prodSummary = new ProductSummary(prod);
        Object row[] = new Object[4];
        row[0] = prod.getTargetPrice();
        row[1] = prodSummary.getNumberAboveTarget();
        row[2] = prodSummary.getNumberBelowTarget();
        row[3] = prodSummary.getSalesRevenues();
        dtm.addRow(row);
    }

    private void populateNewData() {
        int selectedRow = tblProductsCaltalog.getSelectedRow();
        if (selectedRow < 0) {
            return;
        }
        Product prod = (Product) tblProductsCaltalog.getValueAt(selectedRow, 0);
        DefaultTableModel dtm = (DefaultTableModel) jTable12.getModel();
        dtm.setRowCount(0);
        Object row[] = new Object[5];
        row[0] = prod.getQuantity();
        row[1] = prod.getSalesVolume();
        row[2] = prod.getQuantity() * prod.getTargetPrice();
        row[3] = prod.getOrderPricePerformance();
        row[4] = prod.getOrderPricePerformanceIfRecommendedPrice();
        dtm.addRow(row);
    }

}
